import { test, expect } from '@playwright/test'
test('registro, tarea persistida, recordatorio y cierre de sesión', async ({ page }) => {
  await page.goto('/registro')
  await page.getByLabel('Correo electrónico').fill(`test-${Date.now()}@example.com`)
  await page.getByLabel('Contraseña', { exact: true }).fill('Una-clave-segura-2026!')
  await page.getByRole('button', { name: 'Crear mi cuenta' }).click()
  await expect(page.getByRole('heading', { name: 'Un poco de orden. Más espacio para ti.' })).toBeVisible()
  await page.getByRole('button', { name: 'Nueva tarea', exact: true }).click()
  await page.getByLabel('Título de la tarea').fill('Preparar informe de prueba')
  await page.getByRole('button', { name: 'Guardar tarea' }).click()
  await expect(page.getByText('Preparar informe de prueba', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Preparar informe de prueba', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Recordar Preparar informe de prueba' }).click()
  await page.getByLabel('Fecha y hora').fill('2027-01-15T09:30')
  await page.getByRole('button', { name: 'Programar recordatorio' }).click()
  await expect(page.getByRole('status')).toContainText('Recordatorio programado')
  await page.getByRole('button', { name: 'Completar Preparar informe de prueba' }).click()
  await expect(page.getByRole('button', { name: 'Reabrir Preparar informe de prueba' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page.getByRole('button', { name: 'Entrar', exact: true })).toBeVisible()
})
