<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { LayoutDashboard, CalendarDays, MessageCircle, ChartNoAxesCombined, Settings2, Plus, ArrowUpRight, ArrowRight, Check, Bell, X, LogOut, Send, Sparkles, Circle, ChevronRight, Menu } from 'lucide-vue-next'
import { useSession } from '../stores/session'
import { api } from '../services/api'
type Task = { id: string; title: string; description: string | null; status: string; priority: string }
type Reminder = { id: string; task_id: string; scheduled_at: string; timezone: string; recurrence: string; status: string }
const session = useSession(), route = useRoute(), router = useRouter()
const tasks = ref<Task[]>([]), reminders = ref<Reminder[]>([]), messages = ref<any[]>([]), integrations = ref<any>({}), notifications = ref<any[]>([])
const summary = ref({ total_tasks: 0, pending_tasks: 0, completed_tasks: 0, completion_rate: 0 })
const loading = ref(true), busy = ref(false), error = ref(''), toast = ref(''), sidebar = ref(false), filter = ref('all')
const taskModal = ref(false), reminderTask = ref<Task | null>(null), editingTask = ref<string | null>(null)
const title = ref(''), description = ref(''), priority = ref('medium'), dateTime = ref(''), recurrence = ref('none'), chat = ref('')
const timezone = ref('America/Bogota'), responseMode = ref('text')
const nav = [{ path: '/', label: 'Mi día', icon: LayoutDashboard }, { path: '/agenda', label: 'Mis tareas', icon: CalendarDays }, { path: '/asistente', label: 'Asistente', icon: MessageCircle }, { path: '/actividad', label: 'Mi actividad', icon: ChartNoAxesCombined }, { path: '/ajustes', label: 'Configuración', icon: Settings2 }]
const currentTitle = computed(() => nav.find(n => n.path === route.path)?.label || 'Mi día')
const visibleTasks = computed(() => tasks.value.filter(t => filter.value === 'all' || t.status === filter.value))
const activeReminders = computed(() => reminders.value.filter(r => r.status === 'active').sort((a,b) => a.scheduled_at.localeCompare(b.scheduled_at)))
const dateLabel = computed(() => new Intl.DateTimeFormat('es-CO', { weekday: 'long', day: 'numeric', month: 'long', timeZone: timezone.value }).format(new Date()))
function formatDate(date: string) { return new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', timeStyle: 'short', timeZone: timezone.value }).format(new Date(date)) }
function taskName(id: string) { return tasks.value.find(t => t.id === id)?.title || 'Recordatorio' }
async function load() {
  loading.value = true; error.value = ''
  try {
    const [t,r,s,i,p,n] = await Promise.all([api('/tasks'), api('/reminders'), api('/analytics/summary'), api('/integrations/status'), api('/me/preferences'), api('/notifications')])
    tasks.value=t; reminders.value=r; summary.value=s; integrations.value=i; notifications.value=n
    timezone.value=p.timezone; responseMode.value=p.response_mode
    if (route.path === '/asistente') messages.value=await api('/chat/messages')
  } catch(e) { error.value=(e as Error).message } finally { loading.value=false }
}
async function act(fn: () => Promise<void>, success = '') {
  busy.value=true; error.value=''; toast.value=''
  try { await fn(); toast.value=success } catch(e) { error.value=(e as Error).message } finally { busy.value=false }
}
function newTask(task?: Task) { editingTask.value=task?.id ?? null; title.value=task?.title || ''; description.value=task?.description || ''; priority.value=task?.priority || 'medium'; taskModal.value=true }
async function saveTask() { await act(async () => { await api(editingTask.value ? `/tasks/${editingTask.value}` : '/tasks', { method: editingTask.value ? 'PATCH' : 'POST', body:JSON.stringify({ title:title.value, description:description.value, priority:priority.value }) }); taskModal.value=false; await load() }, 'Tarea guardada.') }
async function toggleTask(task: Task) { await act(async () => { await api(`/tasks/${task.id}`, { method:'PATCH', body:JSON.stringify({ status:task.status==='completed'?'pending':'completed' }) }); await load() }, 'Tarea actualizada.') }
async function saveReminder() { await act(async () => {
  // Browser local time is explicit here; the UI labels it separately from the profile timezone.
  const scheduled = new Date(dateTime.value)
  if (!Number.isFinite(scheduled.getTime()) || scheduled.getTime() <= Date.now()) throw new Error('Elige una fecha y hora futuras.')
  await api('/reminders', { method:'POST', body:JSON.stringify({ task_id:reminderTask.value!.id, scheduled_at:scheduled.toISOString(), timezone:Intl.DateTimeFormat().resolvedOptions().timeZone, recurrence:recurrence.value }) }); reminderTask.value=null; await load()
}, 'Recordatorio programado.') }
async function cancelReminder(id: string) { await act(async () => { await api(`/reminders/${id}`, { method:'PATCH', body:JSON.stringify({ status:'cancelled' }) }); await load() }, 'Recordatorio cancelado.') }
async function sendChat() { const content=chat.value.trim(); if (!content) return; await act(async () => { await api('/chat/messages', { method:'POST', body:JSON.stringify({ content }) }); chat.value=''; messages.value=await api('/chat/messages'); await load() }) }
async function savePreferences() { await act(async () => { await api('/me/preferences', { method:'PATCH', body:JSON.stringify({ timezone:timezone.value, response_mode:responseMode.value }) }); await load() }, 'Preferencias guardadas.') }
async function logout() { await act(async () => { await session.logout(); await router.push('/login') }) }
watch(() => route.path, () => { sidebar.value=false; filter.value='all'; load() })
onMounted(load)
</script>
<template>
  <div class="workspace">
    <aside class="sidebar" :class="{ open:sidebar }"><RouterLink to="/" class="brand">pulso<span>✳</span></RouterLink><p class="sidebar-caption">TU ESPACIO PERSONAL</p><nav><RouterLink v-for="item in nav" :key="item.path" :to="item.path" :class="{ active:route.path===item.path }"><component :is="item.icon" :size="19" />{{ item.label }}<span v-if="item.path==='/'" class="nav-dot"></span></RouterLink></nav><div class="sidebar-note"><Sparkles :size="20" /><strong>Haz espacio para ti.</strong><p>Lo importante no siempre es hacer más, sino recordar qué importa.</p></div><div class="profile"><span class="avatar">{{ session.user?.email[0]?.toUpperCase() }}</span><div><strong>Mi cuenta</strong><span>{{ session.user?.email }}</span></div><button class="icon-button" aria-label="Cerrar sesión" @click="logout"><LogOut :size="17" /></button></div></aside>
    <div v-if="sidebar" class="mobile-scrim" @click="sidebar=false"></div>
    <div class="main-area"><header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-menu" aria-label="Abrir menú" @click="sidebar=!sidebar"><Menu :size="20" /></button><span>Mi espacio</span><ChevronRight :size="14" /><strong>{{ currentTitle }}</strong></div><span class="timezone"><span class="live-dot"></span>{{ timezone.replaceAll('_',' ') }}</span></header>
      <main class="content"><div v-if="error" class="error" role="alert">{{ error }} <button class="text-button" @click="load">Reintentar</button></div><div v-if="toast" class="notice" role="status"><Check :size="16" />{{ toast }}<button class="icon-button" aria-label="Cerrar aviso" @click="toast=''"><X :size="15" /></button></div>
        <template v-if="route.path==='/' || route.path==='/agenda'">
          <div class="page-heading"><div><p class="eyebrow">{{ dateLabel }}</p><h1>{{ route.path==='/' ? 'Un poco de orden. Más espacio para ti.' : 'Cada pendiente, en su lugar.' }}</h1><p class="muted">{{ route.path==='/' ? 'Esto es lo que tienes por delante. Vamos paso a paso.' : 'Organiza tus tareas y decide cuándo quieres recordarlas.' }}</p></div><button class="primary" @click="newTask()"><Plus :size="18" />Nueva tarea</button></div>
          <div v-if="route.path==='/'" class="overview-grid"><section class="focus-card"><div class="focus-copy"><span class="pill"><span class="live-dot"></span>A TU RITMO</span><h2>Tu día no tiene que<br>caber en tu cabeza.</h2><p>Deja aquí tus pendientes.<br>Dedícale tu atención a lo que estás haciendo.</p><RouterLink to="/asistente">Abrir mi asistente <ArrowUpRight :size="18" /></RouterLink></div><div class="orbit-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><span class="orbit-center">✳</span><span class="orbit-check"><Check :size="22" /></span></div></section><section class="progress-card"><span class="eyebrow">UN PASO MÁS</span><div class="progress-number">{{ summary.completed_tasks }}<span>/ {{ summary.total_tasks }}</span></div><h3>Tareas completadas</h3><div class="progress-track"><span :style="{ width:`${summary.total_tasks ? summary.completed_tasks / summary.total_tasks * 100 : 0}%` }"></span></div><p class="muted">{{ summary.total_tasks ? 'Cada pequeño avance cuenta.' : 'Tu primer paso empieza con una tarea.' }}</p></section></div>
          <div class="work-grid"><section class="panel task-panel"><div class="section-header"><h2>{{ route.path==='/' ? 'Tus próximos pasos' : 'Mis tareas' }} <span class="count">{{ tasks.length }}</span></h2><span class="muted small">{{ summary.pending_tasks }} pendientes</span></div><div class="tabs"><button v-for="f in [{id:'all',label:'Todas'},{id:'pending',label:'Pendientes'},{id:'completed',label:'Completadas'}]" :key="f.id" :class="{ selected:filter===f.id }" @click="filter=f.id">{{ f.label }}</button></div><div v-if="loading" class="empty">Cargando tu espacio…</div><div v-else-if="!visibleTasks.length" class="empty"><span class="empty-icon"><Check :size="26" /></span><h3>{{ tasks.length ? 'Nada por aquí, de momento.' : 'Un nuevo comienzo.' }}</h3><p>{{ tasks.length ? 'Prueba otro filtro para ver tus tareas.' : 'Añade tu primera tarea. Nosotros guardamos el pendiente; tú eliges el siguiente paso.' }}</p><button v-if="!tasks.length" class="text-button" @click="newTask()">Crear mi primera tarea <ArrowRight :size="16" /></button></div><div v-for="task in visibleTasks" :key="task.id" class="task-row" :class="{ completed:task.status==='completed' }"><button class="task-check" :class="{ checked:task.status==='completed' }" :aria-label="`${task.status==='completed'?'Reabrir':'Completar'} ${task.title}`" :disabled="busy" @click="toggleTask(task)"><Check v-if="task.status==='completed'" :size="14" /></button><button class="task-text" @click="newTask(task)"><strong>{{ task.title }}</strong><span v-if="task.description">{{ task.description }}</span></button><span class="priority" :class="task.priority">{{ {high:'Alta',medium:'Media',low:'Baja'}[task.priority] }}</span><button class="icon-button" :aria-label="`Recordar ${task.title}`" @click="reminderTask=task;dateTime='';recurrence='none'"><Bell :size="17" /></button></div><button class="add-row" @click="newTask()"><Plus :size="17" />Añadir una tarea</button></section>
          <aside class="right-column"><section class="panel reminders-panel"><div class="section-header"><h2><Bell :size="18" />Recordatorios</h2><span class="count">{{ activeReminders.length }}</span></div><p class="muted small">Avisos internos · {{ timezone }}</p><div v-if="!activeReminders.length" class="reminder-empty"><span class="timeline-dot"></span><div><strong>Un momento para lo importante</strong><p>Usa la campana junto a una tarea para programar su aviso.</p></div></div><div v-for="r in activeReminders.slice(0,5)" :key="r.id" class="reminder-item"><span class="timeline-dot"></span><div><small>{{ formatDate(r.scheduled_at) }}</small><strong>{{ taskName(r.task_id) }}</strong><span class="muted small">{{ {none:'Una vez',daily:'Cada día',weekly:'Cada semana'}[r.recurrence] }}</span></div><button class="icon-button" :aria-label="`Cancelar recordatorio ${taskName(r.task_id)}`" @click="cancelReminder(r.id)"><X :size="14" /></button></div></section><section class="whatsapp-card"><div class="section-header"><MessageCircle :size="22" /><span class="status-badge">Próxima integración</span></div><h3>También por WhatsApp.</h3><p>Texto, notas de voz y recordatorios en una conversación.</p><RouterLink to="/ajustes">Ver integraciones <ArrowUpRight :size="16" /></RouterLink></section></aside></div>
        </template>
        <template v-else-if="route.path==='/asistente'"><div class="page-heading"><div><p class="eyebrow">UNA CONVERSACIÓN, MENOS PENDIENTES</p><h1>Piensa en voz alta.<br>Empieza por escribir.</h1><p class="muted">El asistente usa Groq para ayudarte con tus tareas.</p></div><span class="status-badge">{{ integrations.groq?.configured ? 'Groq configurado' : 'Groq sin configurar' }}</span></div><section class="panel chat-panel"><div v-if="!messages.length" class="empty"><Sparkles :size="32" /><h2>¿Qué tienes en mente?</h2><p>Prueba con «Muéstrame mis tareas pendientes» o «Crea una tarea para preparar el informe».</p></div><div v-for="m in messages" :key="m.id" class="message" :class="m.role || m.direction"><small>{{ m.role==='user' || m.direction==='inbound' ? 'Tú' : 'Pulso' }}</small><p>{{ m.content }}</p></div><form class="chat-compose" @submit.prevent="sendChat"><label class="sr-only" for="message">Mensaje al asistente</label><textarea id="message" v-model="chat" rows="2" placeholder="Escribe tu siguiente paso…" :disabled="busy || !integrations.groq?.configured" required maxlength="4000"></textarea><button class="primary" :disabled="busy || !chat.trim() || !integrations.groq?.configured" aria-label="Enviar mensaje"><Send :size="19" /></button></form><p class="muted small">{{ integrations.groq?.configured ? 'Las acciones se confirman después de guardarlas. La voz llegará en el siguiente incremento.' : 'Configura GROQ_API_KEY en el servidor para activar la conversación. Puedes gestionar tus tareas desde la agenda.' }}</p></section></template>
        <template v-else-if="route.path==='/actividad'"><div class="page-heading"><div><p class="eyebrow">PEQUEÑOS PASOS, AVANCES REALES</p><h1>Así vas construyendo tu ritmo.</h1><p class="muted">Un resumen de tus tareas guardadas, sin estimaciones.</p></div></div><div class="metrics-grid"><section v-for="m in [{label:'Tareas creadas',value:summary.total_tasks},{label:'Pendientes',value:summary.pending_tasks},{label:'Completadas',value:summary.completed_tasks}]" :key="m.label" class="panel metric"><p>{{ m.label }}</p><strong>{{ m.value }}</strong></section></div><section class="panel"><div class="section-header"><h2>Historial de avisos</h2><span class="count">{{ notifications.length }}</span></div><p class="muted">Los avisos de este incremento se guardan dentro de la aplicación.</p><div v-if="!notifications.length" class="empty"><Bell :size="24" /><p>Aquí aparecerán los recordatorios que procese el scheduler.</p></div><div v-for="n in notifications" :key="n.id" class="notification-row"><div><strong>{{ n.content || n.title || 'Recordatorio' }}</strong><p class="muted small">{{ n.created_at ? formatDate(n.created_at) : '' }}</p></div><span class="status-badge">{{ n.status }}</span></div></section></template>
        <template v-else><div class="page-heading"><div><p class="eyebrow">A TU MANERA</p><h1>Un asistente que se adapta a ti.</h1><p class="muted">Tus preferencias y el estado real de cada integración.</p></div></div><div class="settings-grid"><form class="panel settings-form" @submit.prevent="savePreferences"><h2>Preferencias personales</h2><label>Zona horaria<input v-model="timezone" required placeholder="America/Bogota"></label><p class="muted small">Usa una zona IANA, como America/Bogota o Europe/Madrid.</p><label>Formato preferido<select v-model="responseMode"><option value="text">Texto</option><option value="audio">Audio (cuando esté disponible)</option><option value="both">Texto y audio (cuando esté disponible)</option></select></label><button class="primary" :disabled="busy">Guardar preferencias</button></form><section class="panel"><h2>Conexiones</h2><div v-for="i in [{key:'groq',name:'Groq',description:'Conversación y agentes de tareas'},{key:'whatsapp',name:'WhatsApp · Evolution API',description:'Transporte pendiente de implementar'},{key:'tts',name:'Voz en español',description:'STT / TTS pendientes de integrar'}]" :key="i.key" class="integration-row"><span class="integration-icon"><MessageCircle v-if="i.key==='whatsapp'" :size="22" /><Sparkles v-else :size="22" /></span><div><strong>{{ i.name }}</strong><p>{{ i.description }}</p></div><span class="status-badge">{{ i.key==='groq' && integrations[i.key]?.configured ? 'Configurado' : 'Pendiente' }}</span></div><p class="muted small">Las credenciales se administran en el servidor o en Dokploy. Nunca se guardan en el navegador.</p></section></div></template>
        <footer class="page-footer"><span>pulso · Un paso a la vez.</span><span>Tu espacio personal</span></footer>
      </main>
    </div>
    <div v-if="taskModal || reminderTask" class="modal-backdrop" @click.self="taskModal=false;reminderTask=null"><section class="modal" role="dialog" aria-modal="true" :aria-label="taskModal?'Nueva tarea':'Programar recordatorio'" @keydown.esc="taskModal=false;reminderTask=null"><div class="section-header"><h2>{{ taskModal ? (editingTask ? 'Editar tarea' : 'Un nuevo paso') : 'Dale su momento' }}</h2><button class="icon-button" aria-label="Cerrar formulario" @click="taskModal=false;reminderTask=null"><X :size="20" /></button></div><form v-if="taskModal" @submit.prevent="saveTask"><label>Título de la tarea<input v-model="title" autofocus required maxlength="200" placeholder="¿Qué quieres hacer?"></label><label>Una nota, si la necesitas<textarea v-model="description" rows="3" maxlength="2000" placeholder="Detalles que te ayuden a empezar"></textarea></label><label>Prioridad<select v-model="priority"><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><p v-if="error" class="error" role="alert">{{ error }}</p><button class="primary full" :disabled="busy">Guardar tarea</button></form><form v-else @submit.prevent="saveReminder"><p class="muted">{{ reminderTask?.title }}</p><label>Fecha y hora<input v-model="dateTime" type="datetime-local" required></label><p class="muted small">Hora de este dispositivo: {{ Intl.DateTimeFormat().resolvedOptions().timeZone }}.</p><label>Repetir<select v-model="recurrence"><option value="none">Una sola vez</option><option value="daily">Cada día</option><option value="weekly">Cada semana</option></select></label><p class="muted small">El aviso se guardará en la aplicación. WhatsApp aún no está conectado.</p><p v-if="error" class="error" role="alert">{{ error }}</p><button class="primary full" :disabled="busy">Programar recordatorio</button></form></section></div>
  </div>
</template>
